FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt requirements-dbt.txt ./

RUN pip install --no-cache-dir -r requirements-dbt.txt

COPY dbt ./dbt
COPY src/analytics_runner.py ./src/analytics_runner.py

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app/src

CMD ["python", "src/analytics_runner.py"]
